name: Test Windows Runner

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: windows-latest
    name: Build MOF
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get Creds & Run Build
        shell: powershell
        run: |
          $username = "${{secrets.CLIENT_ID}}"
          $password = ConvertTo-SecureString "${{secrets.CLIENT_SECRET}}" -AsPlainText -Force
          $psCreds = New-Object System.Management.Automation.PSCredential -ArgumentList ($username, $password)
          .\build.ps1 -AdminCreds $psCreds 
