name: Test Windows Runner

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
jobs:
  job2:
    runs-on: windows-2019
    name: Apply Terraform Plan
    steps:
      - name: Run PS
        run: |
          echo "hello"