name: Test Windows Runner

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on:
  push:
    branches:
      - main
jobs:
  job1:
    runs-on: windows-2019
    name: Test PS
    steps:
      - name: Run PS
        run: |
          Install-Module -Name PowerShellGet -Force
          Install-Module 'PSDscResources' -Verbose -Force
